/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "GPIO.h"
#include "STM32F103x6.h"
#include "lcd.h"


void Clock_INIT(GPIO_t* GPIOx)
{
	if (GPIOx == GPIOA)
		RCC->APB2ENR.IOPAEN = TRUE;
	else if (GPIOx == GPIOB)
		RCC->APB2ENR.IOPBEN = TRUE;
	else if (GPIOx == GPIOC)
		RCC->APB2ENR.IOPCEN = TRUE;
	else if (GPIOx == GPIOD)
		RCC->APB2ENR.IOPDEN = TRUE;
	else if (GPIOx == GPIOE)
		RCC->APB2ENR.IOPEEN = TRUE;
	else //Enable all ports
		RCC->APB2ENR.APB2ENR;
}


int main(void)
{
	Clock_INIT(GPIOA);

	LCD_INIT();
	LCD_WRITE_STRING("HEY");
	_delay_ms(100);
	LCD_CLEAR_SCREEN();
	/* Loop forever */
	while(1)
	{

	}
}
