/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef volatile unsigned int vuint32_t;
#include<stdint.h>
#include<stdlib.h>
#include<stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(vuint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE  0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR	*(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR	*(vuint32_t *)(RCC_BASE + 0x00)

int main(void)
{
	//InitRCC
	RCC_APB2ENR |= 1 << 2;

	//SW register to chose PLL as system clock
	RCC_CFGR |= 0b10 << 0 ;

	//Multiply PLL by 8 to get 32 MHz
	RCC_CFGR |= 0b0110 << 18 ;

	//SetAPB1 to 16 MHz
	RCC_CFGR |= 0b100 << 8 ;

	//SetAPB2 to 8 MHz
	RCC_CFGR |= 0b101 << 11 ;
	
		//PLL On
	RCC_CR |= 1 << 24 ;

	//InitGPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	vuint32_t i = 0;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for(i = 0 ; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for(i = 0 ; i < 5000; i++); // arbitrary delay
	}
}
